openapi: 3.0.0
info:
  title: Hotel Booking API
  version: 1.0.0
  description: API per la gestione delle prenotazioni di hotel.

paths:
  /booking:
    get:
      summary: Recupera tutte le prenotazioni
      operationId: getAllBookings
      responses:
        '200':
          description: Lista di prenotazioni recuperata con successo
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BookingDTO'
        '400':
          description: Errore nella richiesta o di comunicazione
          content:
            application/json:
              schema:
                type: string
        '500':
          description: Errore generico del server
          content:
            application/json:
              schema:
                type: string

    post:
      summary: Crea una nuova prenotazione
      operationId: createBooking
      requestBody:
        required: true    
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookingDTO'
      responses:
        '200':
          description: Prenotazione creata con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingDTO'
        '400':
          description: Errore nella richiesta o di comunicazione
          content:
            application/json:
              schema:
                type: string
        '500':
          description: Errore generico del server
          content:
            application/json:
              schema:
                type: string

  /booking/{id}:
    put:
      summary: Modifica una prenotazione
      operationId: modifyBooking
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          description: ID della prenotazione
          required: true           
      requestBody:
        required: true 
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookingDTO'      
      responses:
        '200':
          description: Prenotazione modificata con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingDTO'
        '400':
          description: Errore nella richiesta o di comunicazione
          content:
            application/json:
              schema:
                type: string
        '500':
          description: Errore generico del server
          content:
            application/json:
              schema:
                type: string

    delete:
      summary: Cancella una prenotazione
      operationId: deleteBooking
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          description: ID della prenotazione
          required: true      
      responses:
        '200':
          description: Prenotazione cancellata con successo
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Errore nella richiesta o di comunicazione
          content:
            application/json:
              schema:
                type: string
        '500':
          description: Errore generico del server
          content:
            application/json:
              schema:
                type: string

  /client:
    get:
      summary: Trova clienti
      operationId: getClients
      responses:
        '200':
          description: Lista di clienti recuperata con successo
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClientDTO'
        '400':
          description: Errore nella richiesta o di comunicazione
          content:
            application/json:
              schema:
                type: string
        '500':
          description: Errore generico del server
          content:
            application/json:
              schema:
                type: string

    post:
      summary: Inserisci un cliente
      operationId: insertClient
      requestBody:
        required: true 
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientDTO' 
      responses:
        '200':
          description: Cliente creato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientDTO'
        '400':
          description: Errore nella richiesta o di comunicazione
          content:
            application/json:
              schema:
                type: string
        '500':
          description: Errore generico del server
          content:
            application/json:
              schema:
                type: string

  /client/{id}:   
    get:
      summary: Trova un cliente
      operationId: findClient
      parameters:
        - name: id
          in: path
          schema:
            type: integer  
          description: ID del cliente
          required: true 
      responses:
        '200':
          description: Cliente recuperato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientDTO'
        '400':
          description: Errore nella richiesta o di comunicazione
          content:
            application/json:
              schema:
                type: string
        '500':
          description: Errore generico del server
          content:
            application/json:
              schema:
               type: string

    put:
      summary: Modifica un cliente
      operationId: modifyClient
      parameters:
        - name: id  
          in: path
          schema:
            type: integer
          description: ID del cliente
          required: true
      requestBody:   
        required: true 
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientDTO'  
      responses:            
        '200':
          description: Cliente modificato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientDTO'
        '400':
          description: Errore nella richiesta o di comunicazione
          content:
            application/json:
              schema:
                type: string
        '500':
          description: Errore generico del server
          content:
            application/json:
              schema:
               type: string

    delete:
      summary: Cancella un cliente
      operationId: deleteClient
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          description: ID del cliente
          required: true
      responses:
        '200':
          description: Cliente cancellato con successo
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Errore nella richiesta o di comunicazione
          content:
            application/json:
              schema:
                type: string
        '500':
          description: Errore generico del server
          content:
            application/json:
              schema:
                type: string

components:
  schemas:
    ClientDTO:
      type: object
      properties:
        nomeOspite:
          type: string
        cognomeOspite:
          type: string
        numeroTelefono:
          type: string  # Modificato da integer a string
        idPrenotazione:
          type: integer

    BookingDTO:
      type: object
      properties:
        dateCheckIn:
          type: string
          format: date-time
        dateCheckOut:
          type: string
          format: date-time